## Higher order functions

In [1]:
twice(f,x) = f(f(x))

twice (generic function with 1 method)

In [4]:
f(x) = x^2
twice(f, 2.0)
twice(x -> x^2, 2.0) #Anonymous function

16.0

## Array Comprehensions and Broadcasting

In [41]:
y = ones(5,1)
for i in 1:5
    y[i] = f(i)
end
y

5×1 Array{Float64,2}:
  1.0
  4.0
  9.0
 16.0
 25.0

In [34]:
f.(1:5) #Broadcast

5-element Array{Int64,1}:
  1
  4
  9
 16
 25

In [33]:
[f(x) for x in 1:5] #comprehension

5-element Array{Int64,1}:
  1
  4
  9
 16
 25

In [11]:
[(x + y, x*y) for x in 1:5, y in 1:5] #Make a multiplication and addition table

5×5 Array{Tuple{Int64,Int64},2}:
 (2, 1)  (3, 2)   (4, 3)   (5, 4)   (6, 5)  
 (3, 2)  (4, 4)   (5, 6)   (6, 8)   (7, 10) 
 (4, 3)  (5, 6)   (6, 9)   (7, 12)  (8, 15) 
 (5, 4)  (6, 8)   (7, 12)  (8, 16)  (9, 20) 
 (6, 5)  (7, 10)  (8, 15)  (9, 20)  (10, 25)

In [19]:
P = [0.6 .4; .2 .8];
ϕ0 = [1.0 0];

#Calculate the transition dynamics of the markov chain
ϕt = [ϕ0 * P^j for j in 0:5]

#Plot 
using Plots
gr()
plot([ϕt[j][1] for j in 1:6]) #Gets the first one.
plot([[1 0] * ϕt[j]' for j in 1:6]) #or multiplying by a vector to extract...


<?xml version="1.0" encoding="utf-8"?>
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 1 
 
 
 2 
 
 
 3 
 
 
 4 
 
 
 5 
 
 
 6 
 
 
 0.4 
 
 
 0.5 
 
 
 0.6 
 
 
 0.7 
 
 
 0.8 
 
 
 0.9 
 
 
 1.0 
 
 
 
 
 
 
 y1

## Interpolation

In [35]:
using QuantEcon
n = 5
xvalues = linspace(0.0, 1.0, n) #grid over values.
f_raw(x) = x^2
yvalues = f_raw.(xvalues)


5-element Array{Float64,1}:
 0.0   
 0.0625
 0.25  
 0.5625
 1.0   

In [37]:
f_int = LinInterp(xvalues, yvalues) #Creates a "function" which interpolates that data
f_int(0.2)
f_int.([0.21, 0.35, 0.5])

3-element Array{Float64,1}:
 0.0525
 0.1375
 0.25  

In [38]:
xdata = 0.0:0.001:1.0
ydata = [f_raw.(xdata), f_int.(xdata)]
plot(xdata, ydata)

<?xml version="1.0" encoding="utf-8"?>
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 0.0 
 
 
 0.2 
 
 
 0.4 
 
 
 0.6 
 
 
 0.8 
 
 
 1.0 
 
 
 0.0 
 
 
 0.2 
 
 
 0.4 
 
 
 0.6 
 
 
 0.8 
 
 
 1.0 
 
<polyline clip-path="url(#clip2402)" style="stroke:#009af9; stroke-width:1; stroke-opacity:1; fill:none" points="
 32.2221,375.813 32.7702,375.813 33.3183,375.812 33.8664,375.81 34.4145,375.808 34.9626,375.804 35.5107,375.8 36.0588,375.796 36.6068,375.79 37.1549,375.784 
 37.703,375.777 38.2511,375.769 38.7992,375.761 39.3473,375.752 39.8954,375.742 40.4435,375.732 40.9916,375.72 41.5397,375.708 42.0878,375.696 42.6359,375.682 
 43.184,375.668 43.7321,375.653 44.2801,375.637 44.8282,375.621 45.3763,375.604 45.9244,375.586 46.4725,375.567 47.0206,375.548 47.5687,375.528 48.1168,375.507 
 48.6649,375.486 49.213,375.464 49.7611,375.441 50.3092,375.417 50.8573,375.393 51.4054,375.368 51.9534,375.342 52.5015,375.315 53.0496,375.288 53.5977,375.26 
 54.1458,375.231 54.6939,375.202 55.242,375.171 55.7901,375.14 56.3382,375.109 56.8863,375.076 57.4344,375.043 57.9825,375.009 58.5306,374.975 59.0787,374.939 
 59.6267,374.903 60.1748,374.867 60.7229,374.829 61.271,374.791 61.8191,374.752 62.3672,374.712 62.9153,374.672 63.4634,374.631 64.0115,374.589 64.5596,374.546 
 65.1077,374.503 65.6558,374.459 66.2039,374.414 66.752,374.369 67.3,374.322 67.8481,374.276 68.3962,374.228 68.9443,374.179 69.4924,374.13 70.0405,374.08 
 70.5886,374.03 71.1367,373.979 71.6848,373.926 72.2329,373.874 72.781,373.82 73.3291,373.766 73.8772,373.711 74.4253,373.655 74.9733,373.599 75.5214,373.542 
 76.0695,373.484 76.6176,373.425 77.1657,373.366 77.7138,373.306 78.2619,373.245 78.81,373.184 79.3581,373.121 79.9062,373.058 80.4543,372.995 81.0024,372.93 
 81.5505,372.865 82.0986,372.799 82.6466,372.733 83.1947,372.665 83.7428,372.597 84.2909,372.528 84.839,372.459 85.3871,372.389 85.9352,372.318 86.4833,372.246 
 87.0314,372.173 87.5795,372.1 88.1276,372.026 88.6757,371.952 89.2238,371.876 89.7719,371.8 90.3199,371.724 90.868,371.646 91.4161,371.568 91.9642,371.489 
 92.5123,371.409 93.0604,371.329 93.6085,371.247 94.1566,371.166 94.7047,371.083 95.2528,371 95.8009,370.915 96.349,370.831 96.8971,370.745 97.4452,370.659 
 97.9932,370.572 98.5413,370.484 99.0894,370.396 99.6375,370.306 100.186,370.217 100.734,370.126 101.282,370.035 101.83,369.942 102.378,369.85 102.926,369.756 
 103.474,369.662 104.022,369.567 104.57,369.471 105.118,369.375 105.667,369.277 106.215,369.18 106.763,369.081 107.311,368.981 107.859,368.881 108.407,368.781 
 108.955,368.679 109.503,368.577 110.051,368.474 110.599,368.37 111.147,368.265 111.696,368.16 112.244,368.054 112.792,367.948 113.34,367.84 113.888,367.732 
 114.436,367.623 114.984,367.514 115.532,367.404 116.08,367.293 116.628,367.181 117.176,367.068 117.725,366.955 118.273,366.841 118.821,366.726 119.369,366.611 
 119.917,366.495 120.465,366.378 121.013,366.261 121.561,366.142 122.109,366.023 122.657,365.903 123.206,365.783 123.754,365.662 124.302,365.54 124.85,365.417 
 125.398,365.294 125.946,365.17 126.494,365.045 127.042,364.919 127.59,364.793 128.138,364.666 128.686,364.538 129.235,364.41 129.783,364.28 130.331,364.15 
 130.879,364.02 131.427,363.888 131.975,363.756 132.523,363.623 133.071,363.49 133.619,363.355 134.167,363.22 134.715,363.085 135.264,362.948 135.812,362.811 
 136.36,362.673 136.908,362.534 137.456,362.395 138.004,362.255 138.552,362.114 139.1,361.972 139.648,361.83 140.196,361.687 140.744,361.543 141.293,361.399 
 141.841,361.253 142.389,361.107 142.937,360.961 143.485,360.813 144.033,360.665 144.581,360.516 145.129,360.367 145.677,360.216 146.225,360.065 146.774,359.913 
 147.322,359.761 147.87,359.608 148.418,359.454 148.966,359.299 149.514,359.144 150.062,358.987 150.61,358.831 151.158,358.673 151.706,358.515 152.254,358.356 
 152.803,358.196 153.351,358.035 153.899,357.874 154.447,357.712 154.995,357.549 155.543,357.386 156.091,357.222 156.639,357.057 157.18

## Expectations and Integration

In [58]:
using Distributions
#Create a binomial distribution.  Number of successes with n samples and p prob of success
N = 10
p = 0.5
dist = Binomial(N,p)

Distributions.Binomial{Float64}(n=10, p=0.5)

In [69]:
NSamples = 100
draws = rand(dist, NSamples)
println("sample mean = $(mean(draws)), actual mean = $(mean(dist))")

sample mean = 5.11, actual mean = 5.0


In [72]:
#To find a funciton... look at Log (n+1).
expec = dot([log(n+1) for n = 0:N], pdf.(dist, support(dist)))

1.7526393207741668

In [71]:
expecrand = sum([log(n+1) for n in draws])/NSamples

1.7713388250096278