## Higher order functions

In [1]:
twice(f,x) = f(f(x))

twice (generic function with 1 method)

In [2]:
f(x) = x^2
twice(f, 2.0)
twice(x -> x^2, 2.0) #Anonymous function

16.0

## Array Comprehensions and Broadcasting

In [3]:
y = ones(5,1)
for i in 1:5
    y[i] = f(i)
end
y

5×1 Array{Float64,2}:
  1.0
  4.0
  9.0
 16.0
 25.0

In [4]:
f.(1:5) #Broadcast

5-element Array{Int64,1}:
  1
  4
  9
 16
 25

In [5]:
[f(x) for x in 1:5] #comprehension

5-element Array{Int64,1}:
  1
  4
  9
 16
 25

In [6]:
[(x + y, x*y) for x in 1:5, y in 1:5] #Make a multiplication and addition table

5×5 Array{Tuple{Int64,Int64},2}:
 (2, 1)  (3, 2)   (4, 3)   (5, 4)   (6, 5)  
 (3, 2)  (4, 4)   (5, 6)   (6, 8)   (7, 10) 
 (4, 3)  (5, 6)   (6, 9)   (7, 12)  (8, 15) 
 (5, 4)  (6, 8)   (7, 12)  (8, 16)  (9, 20) 
 (6, 5)  (7, 10)  (8, 15)  (9, 20)  (10, 25)

## Matrices and Dot Products

In [7]:
[1.0 2.0] * [2.0; 3.0] #Returns an array

1-element Array{Float64,1}:
 8.0

In [8]:
dot([1.0 2.0],[2.0; 3.0]) #Returns the dot product

8.0

In [9]:
#Can use the \cdot <tab> to create the dot product
[1.0 2.0] ⋅ [2.0; 3.0]

8.0

In [10]:
P = [0.6 .4; .2 .8];
ϕ0 = [1.0 0];

#Calculate the transition dynamics of the markov chain
ϕt = [ϕ0 * P^j for j in 0:5]

#Plot 
using Plots
gr()
plot([ϕt[j][1] for j in 1:6]) #Gets the first one.
# or could combine in a comprehension
plot([ [1.0;0.0] ⋅ (ϕ0 * P^j) for j in 1:5])

<?xml version="1.0" encoding="utf-8"?>
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 1 
 
 
 2 
 
 
 3 
 
 
 4 
 
 
 5 
 
 
 0.35 
 
 
 0.40 
 
 
 0.45 
 
 
 0.50 
 
 
 0.55 
 
 
 
 
 
 
 y1

## Interpolation

In [11]:
using QuantEcon
n = 5
xvalues = linspace(0.0, 1.0, n) #grid over values.
f_raw(x) = x^2
yvalues = f_raw.(xvalues)

5-element Array{Float64,1}:
 0.0   
 0.0625
 0.25  
 0.5625
 1.0   

In [12]:
f_int = LinInterp(xvalues, yvalues) #Creates a "function" which interpolates that data
f_int(0.2)
f_int.([0.21, 0.35, 0.5])

3-element Array{Float64,1}:
 0.0525
 0.1375
 0.25  

In [13]:
xdata = 0.0:0.001:1.0
ydata = [f_raw.(xdata), f_int.(xdata)]
plot(xdata, ydata)

<?xml version="1.0" encoding="utf-8"?>
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 0.0 
 
 
 0.2 
 
 
 0.4 
 
 
 0.6 
 
 
 0.8 
 
 
 1.0 
 
 
 0.0 
 
 
 0.2 
 
 
 0.4 
 
 
 0.6 
 
 
 0.8 
 
 
 1.0 
 
<polyline clip-path="url(#clip9002)" style="stroke:#009af9; stroke-width:1; stroke-opacity:1; fill:none" points="
 32.4745,375.869 33.0223,375.868 33.5702,375.867 34.118,375.865 34.6659,375.863 35.2137,375.86 35.7615,375.856 36.3094,375.851 36.8572,375.845 37.4051,375.839 
 37.9529,375.832 38.5007,375.825 39.0486,375.816 39.5964,375.807 40.1443,375.797 40.6921,375.787 41.2399,375.775 41.7878,375.763 42.3356,375.751 42.8835,375.737 
 43.4313,375.723 43.9791,375.708 44.527,375.692 45.0748,375.676 45.6227,375.659 46.1705,375.641 46.7183,375.623 47.2662,375.603 47.814,375.583 48.3619,375.563 
 48.9097,375.541 49.4575,375.519 50.0054,375.496 50.5532,375.472 51.1011,375.448 51.6489,375.423 52.1968,375.397 52.7446,375.37 53.2924,375.343 53.8403,375.315 
 54.3881,375.286 54.936,375.257 55.4838,375.226 56.0316,375.196 56.5795,375.164 57.1273,375.131 57.6752,375.098 58.223,375.064 58.7708,375.03 59.3187,374.995 
 59.8665,374.959 60.4144,374.922 60.9622,374.884 61.51,374.846 62.0579,374.807 62.6057,374.767 63.1536,374.727 63.7014,374.686 64.2492,374.644 64.7971,374.601 
 65.3449,374.558 65.8928,374.514 66.4406,374.469 66.9884,374.424 67.5363,374.378 68.0841,374.331 68.632,374.283 69.1798,374.234 69.7276,374.185 70.2755,374.135 
 70.8233,374.085 71.3712,374.033 71.919,373.981 72.4668,373.929 73.0147,373.875 73.5625,373.821 74.1104,373.766 74.6582,373.71 75.2061,373.654 75.7539,373.597 
 76.3017,373.539 76.8496,373.48 77.3974,373.421 77.9453,373.361 78.4931,373.3 79.0409,373.238 79.5888,373.176 80.1366,373.113 80.6845,373.049 81.2323,372.985 
 81.7801,372.92 82.328,372.854 82.8758,372.787 83.4237,372.72 83.9715,372.652 84.5193,372.583 85.0672,372.514 85.615,372.443 86.1629,372.372 86.7107,372.301 
 87.2585,372.228 87.8064,372.155 88.3542,372.081 88.9021,372.006 89.4499,371.931 89.9977,371.855 90.5456,371.778 91.0934,371.701 91.6413,371.622 92.1891,371.543 
 92.7369,371.464 93.2848,371.383 93.8326,371.302 94.3805,371.22 94.9283,371.137 95.4761,371.054 96.024,370.97 96.5718,370.885 97.1197,370.8 97.6675,370.713 
 98.2153,370.626 98.7632,370.539 99.311,370.45 99.8589,370.361 100.407,370.271 100.955,370.18 101.502,370.089 102.05,369.997 102.598,369.904 103.146,369.81 
 103.694,369.716 104.242,369.621 104.789,369.525 105.337,369.429 105.885,369.332 106.433,369.234 106.981,369.135 107.529,369.036 108.076,368.936 108.624,368.835 
 109.172,368.733 109.72,368.631 110.268,368.528 110.816,368.424 111.364,368.32 111.911,368.214 112.459,368.108 113.007,368.002 113.555,367.894 114.103,367.786 
 114.651,367.677 115.198,367.568 115.746,367.457 116.294,367.346 116.842,367.235 117.39,367.122 117.938,367.009 118.485,366.895 119.033,366.78 119.581,366.665 
 120.129,366.549 120.677,366.432 121.225,366.314 121.772,366.196 122.32,366.077 122.868,365.957 123.416,365.837 123.964,365.715 124.512,365.594 125.06,365.471 
 125.607,365.347 126.155,365.223 126.703,365.098 127.251,364.973 127.799,364.846 128.347,364.719 128.894,364.592 129.442,364.463 129.99,364.334 130.538,364.204 
 131.086,364.073 131.634,363.942 132.181,363.81 132.729,363.677 133.277,363.543 133.825,363.409 134.373,363.274 134.921,363.138 135.469,363.001 136.016,362.864 
 136.564,362.726 137.112,362.587 137.66,362.448 138.208,362.308 138.756,362.167 139.303,362.025 139.851,361.883 140.399,361.74 140.947,361.596 141.495,361.452 
 142.043,361.306 142.59,361.16 143.138,361.014 143.686,360.866 144.234,360.718 144.782,360.569 145.33,360.42 145.877,360.269 146.425,360.118 146.973,359.966 
 147.521,359.814 148.069,359.66 148.617,359.506 149.165,359.352 149.712,359.196 150.26,359.04 150.808,358.883 151.356,358.726 151.904,358.567 152.452,358.408 
 152.999,358.248 153.547,358.088 154.095,357.926 154.643,357.764 155.191,357.602 155.739,357.438 156.286,357.274 156.834,3

## Expectations and Integration

In [14]:
using Distributions, StatPlots
#Create a binomial distribution.  Number of successes with n samples and p prob of success
N = 10
p = 0.5
dist = Binomial(N,p)
plot(dist)

INFO: Precompiling module IterableTables.
INFO: Precompiling module DataValues.
INFO: Precompiling module TableTraitsUtils.
INFO: Precompiling module KernelDensity.
INFO: Precompiling module Loess.


<?xml version="1.0" encoding="utf-8"?>
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 0.0 
 
 
 2.5 
 
 
 5.0 
 
 
 7.5 
 
 
 10.0 
 
 
 0.00 
 
 
 0.05 
 
 
 0.10 
 
 
 0.15 
 
 
 0.20 
 
 
 0.25 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 y1

In [15]:
NSamples = 100
draws = rand(dist, NSamples)
println("sample mean = $(mean(draws)), actual mean = $(mean(dist))")

sample mean = 4.84, actual mean = 5.0


In [16]:
#To find the expectation of a function, for example E( log(n+1) )
distpdf = pdf.(dist, support(dist))

expec = [log(n+1) for n = 0:N] ⋅ distpdf

1.7526393207741668

In [17]:
expecrand = sum([log(n+1) for n in draws])/NSamples

1.7327604454110306