Modified from https://lectures.quantecon.org/jl/discrete_dp.html#exercises

In [13]:
struct SimpleOG
    B
    M
    α
    β
    R
    Q
end

function SimpleOG(;B=10, M=5, α=0.5, β=0.9)

    u(c) = c^α
    n = B + M + 1
    m = M + 1

    R = Matrix{Float64}(n, m)
    Q = zeros(Float64,n,m,n)

    for a in 0:M
        Q[:, a + 1, (a:(a + B)) + 1] = 1 / (B + 1)
        for s in 0:(B + M)
            R[s + 1, a + 1] = a<=s ? u(s - a) : -Inf
        end
    end

    return SimpleOG(B, M, α, β, R, Q)
end

SimpleOG

In [9]:
using QuantEcon
g = SimpleOG()
ddp = DiscreteDP(g.R, g.Q, g.β)
results = solve(ddp, PFI)
fieldnames(results)

5-element Array{Symbol,1}:
 :v       
 :Tv      
 :num_iter
 :sigma   
 :mc      

In [14]:
results.v

16-element Array{Float64,1}:
 19.0174
 20.0174
 20.4316
 20.7495
 21.0408
 21.3087
 21.5448
 21.7693
 21.9827
 22.1882
 22.3845
 22.5781
 22.7611
 22.9438
 23.1153
 23.2776

In [10]:
results.sigma - 1

16-element Array{Int64,1}:
 0
 0
 0
 0
 1
 1
 1
 2
 2
 3
 3
 4
 5
 5
 5
 5

In [11]:
using Plots
gr()
bar(stationary_distributions(results.mc)[1], label="stationary dist")

<?xml version="1.0" encoding="utf-8"?>
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 3 
 
 
 6 
 
 
 9 
 
 
 12 
 
 
 15 
 
 
 0.00 
 
 
 0.02 
 
 
 0.04 
 
 
 0.06 
 
 
 0.08 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 stationary dist

In [12]:
g_2 = SimpleOG(β=0.99)

ddp_2 = DiscreteDP(g_2.R, g_2.Q, g_2.β)
results_2 = solve(ddp_2, PFI)
std_2 = stationary_distributions(results_2.mc)[1]
bar(std_2, label="stationary dist")

<?xml version="1.0" encoding="utf-8"?>
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 3 
 
 
 6 
 
 
 9 
 
 
 12 
 
 
 15 
 
 
 0.00 
 
 
 0.02 
 
 
 0.04 
 
 
 0.06 
 
 
 0.08 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 stationary dist